---

base_locale: en
locales: [en]

ignore_unused:
  - "decidim.components.Chatbot.name"
  - "decidim.chatbot.admin.menu.chatbot"
  - "decidim.chatbot.admin.settings.toggle.*"
  - "decidim.chatbot.providers.*"
  - "decidim.chatbot.workflows.*.title"

ignore_missing:
  - decidim.participatory_processes.scopes.global
